version: "3.8"

services:
  datatourisme:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./public:/app/public
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8080
